### ISSUE TITLE
Скрипт сборки + нейминг коммитов

### ISSUE THREAD

**Issue by Ilihon** [1C-Connect/1cconnect-example-bot#1]
Привет, в документации по запуску упоминается скрипт ./build.sh, но в репозитории такого не нашёл. 

В истории коммитов заметил забавный нейминг у коммитов. Не слишком резко для официального репозитория дистрибьютора?)
![изображение_2023-11-17_124917895](https://github.com/1C-Connect/1cconnect-example-bot/assets/29188260/fe53495d-5440-40ab-bffc-b06bb15dfe7c)

**Comment by polyn0m** [comment]
@Ilihon, добрый день.

Спасибо за замечания, история комитов очищена от лишнего.

Документация, которую вам передали коллеги, относится к другому боту. Его исходный код опубликован здесь: https://github.com/1C-Connect/1cconnect-text-bot
